name: Github Autobuild macOS
on: [ push, pull_request ]
env:
  CCACHE_COMPRESS: exists means true
  CCACHE_SLOPPINESS: include_file_ctime,include_file_mtime,time_macros
jobs:
  test-macos:
    name: Build and run tests in macOS
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Use XCode 12.2 for Big Sur
      if: contains(matrix.os, 'macos-11.0')
      run: sudo xcode-select -s "/Applications/Xcode_12.2.app"
    - name: Install dependencies
      run: |
        brew install autoconf automake libtool
        brew install ccache
        brew search boost
        brew install bitshares/boost/boost@1.69
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Configure
      run: |
        mkdir -p _build
        pushd _build
        cmake -D CMAKE_BUILD_TYPE=Release \
              -D CMAKE_C_COMPILER_LAUNCHER=ccache \
              -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -D BOOST_ROOT=/usr/local/opt/boost@1.69 \
              -D OPENSSL_ROOT_DIR=/usr/local/opt/openssl \
              ..
        popd
    - name: Load Cache
      uses: actions/cache@v1
      with:
        path: ccache
        key: ccache-osx-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ccache-osx-${{ github.ref }}-
          ccache-osx-
    - name: Build
      run: |
        export CCACHE_DIR="$GITHUB_WORKSPACE/ccache"
        mkdir -p "$CCACHE_DIR"
        make -j 2 -C _build
        df -h
    - name: Unit-Tests
      run: |
        pushd _build/tests
        ./all_tests -l message
        ./bloom_test -- README.md
        ./ecc_test README.md
        ./hmac_test
        ./task_cancel_test
