on: [ push, pull_request ]
jobs:
  test-release:
    name: Build and run tests in Release mode
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
                     parallel \
                     libboost-thread-dev \
                     libboost-iostreams-dev \
                     libboost-date-time-dev \
                     libboost-system-dev \
                     libboost-filesystem-dev \
                     libboost-program-options-dev \
                     libboost-chrono-dev \
                     libboost-test-dev \
                     libboost-context-dev \
                     libboost-regex-dev \
                     libboost-coroutine-dev
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Configure
      run: |
        mkdir -p _build
        pushd _build
        cmake -D CMAKE_BUILD_TYPE=Release \
              -D CMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON \
              -D CMAKE_C_COMPILER=gcc \
              -D CMAKE_CXX_COMPILER=g++ \
              ..
        popd
    - name: Build
      run: |
        make -j 2 -C _build
    - name: Test
      run: |
        parallel echo Running {}\; sh -c "_build/tests/{}" <<_EOT_
        all_tests
        bloom_test README.md
        ecc_test README.md
        hmac_test
        task_cancel_test
        _EOT_
  test-debug:
    name: Build and run tests in Debug mode
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
                     parallel \
                     libboost-thread-dev \
                     libboost-iostreams-dev \
                     libboost-date-time-dev \
                     libboost-system-dev \
                     libboost-filesystem-dev \
                     libboost-program-options-dev \
                     libboost-chrono-dev \
                     libboost-test-dev \
                     libboost-context-dev \
                     libboost-regex-dev \
                     libboost-coroutine-dev
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Configure
      run: |
        mkdir -p _build
        pushd _build
        cmake -D CMAKE_BUILD_TYPE=Debug \
              -D CMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON \
              -D CMAKE_C_COMPILER=gcc \
              -D CMAKE_CXX_COMPILER=g++ \
              ..
        popd
    - name: Build
      run: |
        make -j 2 -C _build
    - name: Test
      run: |
        parallel echo Running {}\; sh -c "_build/tests/{}" <<_EOT_
        all_tests
        bloom_test README.md
        ecc_test README.md
        hmac_test
        task_cancel_test
        _EOT_
